name: Hardhat Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'  # Add this line to fetch submodules
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'
    - name: Create .env
      run: |
        cp .env.sample .env
    - name: Install dependencies
      run: |
        npm ci
        cd eigensdk-js  # Navigate to the submodule directory
        npm ci  # Install dependencies for the submodule
        cd ..  # Return to the main project directory
    - name: Run Hardhat tests
      run: npx hardhat test